{
  "hash": "a1f2be4c83da41c10b24d296c6f67120",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Regresión lineal\"\ndate: \"2026-06-01\"\nimage: Regresión lineal.png\n---\n\n## 🔮 El oráculo\n\nSi la inferencia era probar la sopa, la **regresión lineal** es nuestro intento de ser adivinos. Imagina que quieres saber cuánto mide un árbol sin tener que treparlo, solo mirando cuánto mide su tronco. Básicamente, le decimos al ordenador: \"Oye, aquí tienes unos datos, ¡encuéntrame la línea que mejor une estos puntos!\". Es como intentar unir los puntos de un dibujo infantil, pero con matemáticas serias.\n\n## 📝 Marco Teórico\n\n-   **El Modelo:** $$Y = \\beta_0 + \\beta_1 X + \\varepsilon$$. Intentamos explicar una variable dependiente (\\$Y\\$) mediante una independiente (\\$X\\$).\n\n-   **Mínimos Cuadrados (MCO):** Buscamos minimizar la suma de los cuadrados de los errores: $$\\sum (Y_i - \\hat{Y}_i)^2$$.\n\n-   **Interpretación:** $\\beta_1$ nos dice cuánto cambia $Y$ por cada unidad que aumenta $X$.\n\n-   **Supuestos:** Linealidad, homocedasticidad (varianza constante), independencia y normalidad de los residuos.\n\n-   **Inferencia:** Construimos intervalos de confianza para los coeficientes y contrastes de significación ($t$-test) para ver si $\\beta_1 \\neq 0$.\n\n## 🌳 Análisis práctico: Dataset `trees`\n\nQueremos predecir el volumen de madera (`Volume`) a partir de la altura (`Height`).\n\n```         \n \n```\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(trees)\n\n# Ajuste del modelo\nmodelo <- lm(Volume ~ Height, data = trees)\n\n# Resumen del modelo\nsummary(modelo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Volume ~ Height, data = trees)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-21.274  -9.894  -2.894  12.068  29.852 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -87.1236    29.2731  -2.976 0.005835 ** \nHeight        1.5433     0.3839   4.021 0.000378 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 13.4 on 29 degrees of freedom\nMultiple R-squared:  0.3579,\tAdjusted R-squared:  0.3358 \nF-statistic: 16.16 on 1 and 29 DF,  p-value: 0.0003784\n```\n\n\n:::\n:::\n\n\n### Interpretación de Resultados\n\n1.  **Estimación:** Nuestro modelo es $$\\widehat{Volume} = -87.12 + 1.54 \\cdot Height$$.\n\n    -   Por cada pie que aumenta la altura, el volumen aumenta de media 1.54 unidades.\n\n2.  **Contraste de significación:** El $p$-valor asociado a `Height` es 4\\times 10^{-4}. Como es menor a 0.05, el efecto de la altura sobre el volumen es **estadísticamente significativo**.\n\n3.  **Intervalo de Confianza:**\n\n\n    ::: {.cell}\n    \n    ```{.r .cell-code}\n    ### Diagnóstico del Modelo\n    #| echo: true\n    #| warning: false\n    confint(modelo, \"Height\", level = 0.95)\n    ```\n    \n    ::: {.cell-output .cell-output-stdout}\n    \n    ```\n              2.5 %   97.5 %\n    Height 0.758249 2.328451\n    ```\n    \n    \n    :::\n    \n    ```{.r .cell-code}\n    # Para comprobar los supuestos, veamos cómo se ajusta:\n    plot(modelo, which = 1) # Gráfico de residuos vs ajustados\n    ```\n    \n    ::: {.cell-output-display}\n    ![](index_files/figure-html/unnamed-chunk-2-1.png){width=672}\n    :::\n    :::\n\n\nComo no conocemos la población completa, el intervalo nos da el margen de error. Podemos decir con un **95% de confianza** que el efecto real de la altura sobre el volumen está entre **0.76 y 2.33** unidades por pie.\n\nSi los puntos están repartidos al azar sin formar patrones claros (como una \"nube\" sin forma), ¡nuestros supuestos de homocedasticidad e independencia se cumplen!\n\n¡Ahora sí que hemos cerrado el círculo: de la muestra a la predicción!\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}